# Generated by Django 6.0 on 2025-12-12 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
