# Generated by Django 6.0 on 2025-12-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_vote_date_of_birth_vote_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
