# Generated by Django 6.0 on 2025-12-12 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_vote_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=9, null=True),
        ),
    ]
