# Generated by Django 6.0 on 2025-12-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_alter_vote_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='voter_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
