# Generated by Django 6.0 on 2025-12-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_vote_voter_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='age',
        ),
    ]
