# Generated by Django 5.2.7 on 2025-12-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_remove_vote_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='aadhar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
