# Generated by Django 5.2.7 on 2025-12-24 08:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_vote_aadhar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
